
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 09 15:19:49 GMT-06:00 2024
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NEGATIVO = 12;
  public static final int MayorQue = 5;
  public static final int Multiplicacion = 9;
  public static final int CerrarParentesis = 3;
  public static final int Division = 10;
  public static final int AbrirParentesis = 2;
  public static final int EOF = 0;
  public static final int Suma = 7;
  public static final int error = 1;
  public static final int Igual = 6;
  public static final int MenorQue = 4;
  public static final int Numero = 11;
  public static final int Resta = 8;
}

